always_for_in = true
always_use_return = true
annotate_untyped_fields_with_any = true
conditional_to_if = true
format_docstrings = true
margin = 92
remove_extra_newlines = true
whitespace_in_kwargs = true
whitespace_ops_in_indices = true
whitespace_typedefs = true
