name = "TernaryPlots"
uuid = "1f5e811d-5acb-4dfc-9a45-b3a27d369aae"
authors = ["Martin Smit <jacobusmmsmit@gmail.com> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
julia = "1.6"
RecipesBase = "1.1.2"